title: "Chinchuthakun Worameth"
author: "Chinchuthakun Worameth"
description: "To be inserted..."
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: Home, file: "index.md"}
  - {title: Blogs, file: "blog.html"}
  - {title: About, file: "about.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: CV, icon: file, url: "https://drive.google.com/file/d/1PjHykM3w2Y5q0KP56I-UHZLKEUuHLil6/view?usp=sharing"}
  - {title: Mail, icon: envelope, url: "mailto:hw.55.m.woramet@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/sincostanx"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/worameth-chinchuthakun-7b3704148/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
